# Generated by Django 5.0.6 on 2024-07-03 10:12

import ckeditor_uploader.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="content",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="contents",
                to="base_app.category",
            ),
        ),
        migrations.AlterField(
            model_name="content",
            name="text",
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
