# Generated by Django 5.0.6 on 2024-07-03 12:23

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("base_app", "0002_alter_content_category_alter_content_text"),
    ]

    operations = [
        migrations.AlterField(
            model_name="content",
            name="text",
            field=ckeditor.fields.RichTextField(),
        ),
    ]
