# Generated by Django 5.0.6 on 2024-07-04 04:31

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("base_app", "0003_alter_content_text"),
    ]

    operations = [
        migrations.AlterField(
            model_name="content",
            name="text",
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
