# Generated by Django 5.0.6 on 2024-07-09 05:54

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base_app", "0005_content_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="content",
            name="music",
            field=models.FileField(
                blank=True, default=None, null=True, upload_to="musics/"
            ),
        ),
        migrations.AlterField(
            model_name="content",
            name="text",
            field=ckeditor_uploader.fields.RichTextUploadingField(
                blank=True, null=True
            ),
        ),
        migrations.AlterField(
            model_name="content",
            name="title",
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
