# Generated by Django 5.0.6 on 2024-07-09 09:54

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base_app", "0006_content_music_alter_content_text_alter_content_title"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="content",
            name="image",
        ),
        migrations.RemoveField(
            model_name="content",
            name="text",
        ),
        migrations.AddField(
            model_name="content",
            name="image_for_ertak",
            field=models.FileField(
                blank=True,
                default=None,
                null=True,
                upload_to="images/",
                verbose_name="ertak uchun rasm",
            ),
        ),
        migrations.AddField(
            model_name="content",
            name="text_for_ertak",
            field=ckeditor_uploader.fields.RichTextUploadingField(
                blank=True, null=True, verbose_name="text ertak uchun"
            ),
        ),
    ]
