# Generated by Django 5.0.6 on 2024-07-09 10:20

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base_app", "0007_remove_content_image_remove_content_text_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="content",
            name="music",
        ),
        migrations.AddField(
            model_name="content",
            name="music_for_sher",
            field=models.FileField(
                blank=True,
                default=None,
                null=True,
                upload_to="musics/",
                verbose_name="sher mp3",
            ),
        ),
        migrations.AddField(
            model_name="content",
            name="qoshiq",
            field=models.FileField(
                blank=True,
                default=None,
                null=True,
                upload_to="videos",
                verbose_name="qo'shiq file",
            ),
        ),
        migrations.AddField(
            model_name="content",
            name="rasm",
            field=models.FileField(
                blank=True,
                default=None,
                null=True,
                upload_to="images/",
                verbose_name="Rasmlar",
            ),
        ),
        migrations.AddField(
            model_name="content",
            name="text_for_oyin",
            field=ckeditor_uploader.fields.RichTextUploadingField(
                blank=True, default=None, null=True, verbose_name="O'yinlar uchun text"
            ),
        ),
        migrations.AddField(
            model_name="content",
            name="text_for_sher",
            field=ckeditor_uploader.fields.RichTextUploadingField(
                blank=True, default=None, null=True, verbose_name="sher uchun text"
            ),
        ),
        migrations.AddField(
            model_name="content",
            name="video_for_mohir",
            field=models.FileField(
                blank=True,
                default=None,
                null=True,
                upload_to="videos/",
                verbose_name="mohir qo'llar uchun video",
            ),
        ),
    ]
